# Generated by Django 5.1.2 on 2024-10-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='images/brand/logo/'),
        ),
    ]
